# Site settings
title: Video Mirror
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Ever want to watch the mirrored version of a video? That's what the site's for. Paste your URL and enjoy in all its mirrored glory.
baseurl: "/video-mirror/" # the subpath of your site, e.g. /blog/
url: "http://theadamparker.github.io/video-mirror/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
